# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Building KurtsNonCoreWebApplication...'
  inputs:
    solution: '**/KurtsNonCoreWebApplication.csproj'
    vsVersion: '16.0'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'Building KurtsConsoleApp...'
  inputs:
    solution: '**/KurtsConsoleApp.csproj'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    logFileVerbosity: 'detailed'

- task: MSBuild@1
  displayName: 'Building 1 KurtsNonCoreConsoleApp...'
  inputs:
    solution: '**/KurtsNonCoreConsoleApp.csproj'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '(buildConfiguration)'
    restoreNugetPackages: true


- task: VSBuild@1
  displayName: 'Building 2 KurtsNonCoreConsoleApp...'
  inputs:
    solution: '**\KurtsNonCoreConsoleApp.csproj'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '(buildConfiguration)'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
    createLogFile: true
    logFileVerbosity: 'diagnostic'

